name: Deploy docker build and push

on:
    workflow_dispatch:

jobs:
    build-and-deploy-in-acr:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./app
        steps:
            - uses: actions/checkout@v2
            
            - uses: azure/docker-login@v1
              with:
                login-server: ${{ secrets.ACR_REGISTRY }}
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}
            - run: |
                docker build . -t ${{ secrets.ACR_REGISTRY }}/${{ vars.APP_SERVICE }}:${{ github.sha }} -t ${{ secrets.ACR_REGISTRY }}/${{ vars.APP_SERVICE }}:latest
                docker push ${{ secrets.ACR_REGISTRY }}/${{ vars.APP_SERVICE }}